#!/usr/bin/env python3

########################################################################
# Title:   Certificate Generator
# Author:  Doug Johnson - doug@tinydragonsolutions.com
# Version: 7.0 (Python rewrite of Perl v6.0)
#
# Assumptions:
#   1) Running on Linux with Apache httpd and mod_cgi
#   2) Root CA is installed in /var/www/cgi-bin/certs/root-ca
#   3) Subordinate CA is installed in /var/www/cgi-bin/certs/sub-ca
#   4) OpenSSL is installed at /usr/bin/openssl
#   5) Config file exists at /etc/certgen/certgen.ini
#
# Config file format (/etc/certgen/certgen.ini):
#   [paths]
#   root_ca_dir = /var/www/cgi-bin/certs/root-ca
#   sub_ca_dir  = /var/www/cgi-bin/certs/sub-ca
#
#   [ca]
#   key_password = <your-ca-key-password>
#
# Set Up Instructions:
#   1) Deploy Apache with mod_cgi enabled
#   2) chmod 755 /var/www/cgi-bin/Cert_Gen.cgi
#   3) chown -R apache:apache /var/www/cgi-bin/certs
#   4) Create /etc/certgen/certgen.ini with the CA key password
#      chmod 640 /etc/certgen/certgen.ini
#      chown root:apache /etc/certgen/certgen.ini
#
# Testing (command line):
#   QUERY_STRING="f_liability=yes" ./Cert_Gen.cgi
#   QUERY_STRING="f_liability=yes&f_customer=TheHorde&f_fqdn=uc.thehorde&f_gwClient=bem" \
#     REQUEST_METHOD=GET ./Cert_Gen.cgi
########################################################################

import cgi
import cgitb
import configparser
import html
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

cgitb.enable()

CONFIG_FILE = Path("/etc/certgen/certgen.ini")
CGI_SCRIPT  = "/cgi-bin/Cert_Gen.cgi"
OPENSSL     = "/usr/bin/openssl"

DEVICE_TYPES = {
    "gateway":    ("GW_Cert.txt",              "userInterface"),
    "addia":      ("GW_Cert.txt",              "identityInsertion"),
    "bem":        ("BEM_Cert.txt",             "userInterface"),
    "trustlevel": ("TrustLevel_Cert.txt",      "trustlevel"),
    "endpoint":   ("Endpoint_Client_Cert.txt", "identityActivation"),
    "DEV":        ("DEV_Custom_SAN_Cert.txt",  None),
}


# ─── Config ───────────────────────────────────────────────────────────────────

def load_config():
    if not CONFIG_FILE.exists():
        abort(f"Configuration file not found: {CONFIG_FILE}")
    config = configparser.ConfigParser()
    config.read(CONFIG_FILE)
    return config


# ─── HTML helpers ─────────────────────────────────────────────────────────────

def emit_http_header():
    sys.stdout.write("Content-Type: text/html\r\n\r\n")

def page_header(title="INSERT_COMPANY_NAME Certificate Generation"):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{html.escape(title)}</title>
  <link rel="stylesheet" type="text/css" href="../styles.css">
</head>
<body>
<h1><center>INSERT_COMPANY_NAME Certificate Generation</center></h1>
<h2><font color="red"><center>***For use with TAC 4.1 and beyond ONLY***</center></font></h2>
"""

def page_footer():
    return "</body>\n</html>\n"

def abort(message):
    emit_http_header()
    print(page_header())
    print(f"<p><strong>Error:</strong> {html.escape(str(message))}</p>")
    print(page_footer())
    sys.exit(1)

def e(value):
    return html.escape(str(value))


# ─── Step 0: Liability notice ─────────────────────────────────────────────────

def show_liability_form():
    print(f"""<h2><center>Liability Notice</center></h2>

<p>The INSERT_COMPANY_NAME software uses certificates to identify various INSERT_COMPANY_NAME internal system
components, providing both authentication and encryption. The INSERT_COMPANY_NAME solution will not
function without this level of operational security being in place.</p>

<p>These certificates are currently generated by a certificate authority (CA) provided and
hosted by INSERT_COMPANY_NAME. INSERT_COMPANY_NAME is transitioning from providing and hosting the CA to using
a recognized certificate provider and certificate authority. When this transition is
complete, new certificates will be issued to all existing customers at no additional charge.</p>

<p>INSERT_COMPANY_NAME does not accept any liability associated with using internally generated
certificates, including any liability associated with providing certificate authority
services to customers. Should a customer have their own CA that they would like to use
with the INSERT_COMPANY_NAME solution, the software supports this today.</p>

<p>Do you understand this liability notice and, if this is for a customer deployment,
have you explained this to them so that they accept it?</p>

<form action="{CGI_SCRIPT}" method="post">
  <table>
    <tr>
      <td>Do you accept?</td>
      <td>
        <select name="f_liability">
          <option value="">Select a Response</option>
          <option value="yes">Yes</option>
          <option value="no">No</option>
        </select>
      </td>
    </tr>
  </table>
  <p><input type="submit" value="Submit"></p>
</form>
""")


# ─── Step 1: Customer / device info ──────────────────────────────────────────

def show_customer_form():
    # SAN help text is shown inline for DEV mode via JavaScript
    san_help = r"""
<br>
<table>
  <thead><tr><th colspan="2">Supported SAN Tags</th></tr></thead>
  <tbody>
    <tr><td>DNS</td><td>for FQDN or hostname</td></tr>
    <tr><td>IP</td><td>for IPv4 or IPv6</td></tr>
    <tr><td>URI</td><td>for Certificate Group</td></tr>
  </tbody>
</table>
<br>
Tags and values are separated by a colon (<code>:</code>), entries by a comma (<code>,</code>).
<br><br>
Example: <code>DNS:org.example.com,IP:1.1.1.1,URI:organization://org.example.com/Agent/userInterface</code>
<br><br>
<table>
  <thead><tr><th align="left">Examples</th><th></th></tr></thead>
  <tbody>
    <tr><td>Gateway (FQDNs only)</td>
        <td><code>DNS:org.example.com,DNS:br-active.example.com,URI:organization://org.example.com/Agent/userInterface</code></td></tr>
    <tr><td>Gateway (FQDNs + IPs)</td>
        <td><code>DNS:org.example.com,IP:1.1.1.1,DNS:br-active.example.com,IP:2.2.2.2,URI:organization://org.example.com/Agent/userInterface</code></td></tr>
    <tr><td>BEM</td>
        <td><code>DNS:org.example.com,URI:organization://org.example.com/Agent/userInterface</code></td></tr>
    <tr><td>AD Agent</td>
        <td><code>DNS:org.example.com,URI:organization://org.example.com/Agent/identityInsertion</code></td></tr>
    <tr><td>Endpoint</td>
        <td><code>DNS:org.example.com,URI:organization://org.example.com/Agent/identityActivation</code></td></tr>
    <tr><td>Trust Level</td>
        <td><code>DNS:org.example.com,URI:organization://org.example.com/Agent/trustlevel</code></td></tr>
  </tbody>
</table>"""

    # Escape the san_help string for safe embedding in a JS template literal.
    # Backticks and ${} need escaping inside JS template literals.
    san_help_js = san_help.replace("\\", "\\\\").replace("`", r"\`").replace("${", r"\${")

    print(f"""<p>Please provide the following information:</p>

<form action="{CGI_SCRIPT}" method="post">
<script>
function handleSelect(entity) {{
  var row_customer =
    '<tr><td>Customer Name:</td>' +
    '<td><input type="text" name="f_customer" value=""></td>' +
    '<td><i>No spaces &mdash; the certificate will still generate but may not display.</i></td></tr>';

  var row_fqdn =
    '<tr><td>Fully Qualified Domain Name:</td>' +
    '<td><input type="text" name="f_fqdn" value=""></td>' +
    '<td><i>If there is no FQDN, use hostname.customer here.</i></td></tr>';

  var row_gwsvc_fqdn =
    '<tr><td>Gateway Services FQDN:</td>' +
    '<td><input type="text" name="f_gwSvcsFqdn" value=""></td>' +
    '<td><i><b>***GATEWAYS ONLY***</b> No spaces. Type carefully.</i></td></tr>';

  var row_custom_san =
    '<tr><td>Custom SAN:</td>' +
    '<td colspan="2"><input type="text" name="f_custom_san" value="" style="width:100%"></td></tr>';

  var row_spacer = '<tr><td colspan="3"><br><br></td></tr>';

  var san_help = `{san_help_js}`;

  var contents = "";
  var san_section = document.getElementById("mySANHelp");

  switch (entity) {{
    case "gateway":
      contents = row_customer + row_spacer + row_fqdn + row_spacer + row_gwsvc_fqdn;
      san_section.innerHTML = "";
      break;
    case "bem":
    case "addia":
    case "trustlevel":
    case "endpoint":
      contents = row_customer + row_spacer + row_fqdn;
      san_section.innerHTML = "";
      break;
    case "DEV":
      contents = row_customer + row_spacer + row_custom_san;
      san_section.innerHTML = san_help;
      break;
    default:
      contents = "";
      san_section.innerHTML = "";
  }}

  document.getElementById("myTableContainer").innerHTML = contents;
}}
</script>

<h2>Is this request for a Gateway, BEM, or Client?</h2>
<select name="f_gwClient" onchange="handleSelect(this.value)">
  <option value="">Select a Response</option>
  <option value="gateway">Gateway</option>
  <option value="bem">BEM</option>
  <option value="addia">Active Directory DIA</option>
  <option value="trustlevel">Trust Level</option>
  <option value="endpoint">Endpoint Client</option>
  <option value="DEV">DEV</option>
</select>
<i>AD DIA, Trust Level, and Endpoint Client are clients.</i>
<br><br>

<table><tbody id="myTableContainer"></tbody></table>
<p><input type="submit" value="Submit"></p>
<div id="mySANHelp"></div>
</form>
""")


# ─── Step 2: CSR input ────────────────────────────────────────────────────────

def validate_fields(fields):
    if not fields["customer"]:
        return "You must enter a customer name."
    gw = fields["gw_client"]
    if not gw:
        return "You must select a device type."
    if gw == "gateway" and (not fields.get("fqdn") or not fields.get("gw_svcs_fqdn")):
        return "Gateways require both an FQDN and a Gateway Services FQDN."
    if gw in ("bem", "addia", "trustlevel", "endpoint") and not fields.get("fqdn"):
        return "This device type requires an FQDN."
    if gw == "DEV" and not fields.get("custom_san"):
        return "DEV mode requires a custom SAN."
    return None

def show_csr_form(fields):
    print(f"<h2>Customer Details</h2>")
    print(f"<p>Customer: {e(fields['customer'])}</p>")
    if fields["gw_client"] == "DEV":
        print(f"<p>Custom SAN: {e(fields.get('custom_san', ''))}</p>")
    else:
        if fields.get("fqdn"):
            print(f"<p>FQDN: {e(fields['fqdn'])}</p>")
        if fields.get("gw_svcs_fqdn"):
            print(f"<p>Gateway Services FQDN: {e(fields['gw_svcs_fqdn'])}</p>")
        print(f"<p>Device type: {e(fields['gw_client'])}</p>")

    print(f"""<p>Paste your CSR below:</p>
<form action="{CGI_SCRIPT}" method="post">
  <table>
    <tr><td><textarea rows="30" cols="78" name="f_csr"></textarea></td></tr>
  </table>
  <p></p>
  <input type="hidden" name="f_customer"   value="{e(fields['customer'])}">
  <input type="hidden" name="f_fqdn"       value="{e(fields.get('fqdn', ''))}">
  <input type="hidden" name="f_gwSvcsFqdn" value="{e(fields.get('gw_svcs_fqdn', ''))}">
  <input type="hidden" name="f_gwClient"   value="{e(fields['gw_client'])}">
  <input type="hidden" name="f_custom_san" value="{e(fields.get('custom_san', ''))}">
  <input type="submit" value="Submit">
</form>
""")


# ─── Step 3: Generate certificate ────────────────────────────────────────────

def parse_csr_subject(csr_text, work_dir):
    csr_path = work_dir / "csrFile.txt"
    csr_path.write_text(csr_text)

    result = subprocess.run(
        [OPENSSL, "req", "-in", str(csr_path), "-noout", "-text"],
        capture_output=True, text=True
    )

    pattern = re.compile(
        r"^\s*Subject:\s*C=(.*?),\s*ST=(.*?),\s*L=(.*?),\s*O=(.*?),\s*OU=(.*?),\s*CN=(.*)",
        re.IGNORECASE
    )
    for line in result.stdout.splitlines():
        m = pattern.match(line)
        if m:
            return {
                "country":     m.group(1).strip(),
                "state":       m.group(2).strip(),
                "locale":      m.group(3).strip(),
                "org":         m.group(4).strip(),
                "org_unit":    m.group(5).strip(),
                "common_name": m.group(6).strip(),
            }
    return {}

def build_san(fields):
    gw_client  = fields["gw_client"]
    fqdn       = fields.get("fqdn", "")
    gw_svcs_fqdn = fields.get("gw_svcs_fqdn", "")
    custom_san = fields.get("custom_san", "")

    if gw_client == "DEV":
        return custom_san

    _, agent_path = DEVICE_TYPES.get(gw_client, ("", "userInterface"))
    sans = []
    if fqdn:
        sans.append(f"DNS:{fqdn}")
    if gw_svcs_fqdn and gw_client == "gateway":
        sans.append(f"DNS:{gw_svcs_fqdn}")
    if fqdn and agent_path:
        sans.append(f"URI:organization://{fqdn}/Agent/{agent_path}")
    return ",".join(sans)

def generate_certificate(fields, csr_text, config, base_dir):
    sub_ca_dir  = Path(config.get("paths", "sub_ca_dir"))
    root_ca_dir = Path(config.get("paths", "root_ca_dir"))
    ca_password = config.get("ca", "key_password")

    customer_slug = fields["customer"].replace(" ", "")
    certs_dir     = base_dir / "certs" / "customers" / customer_slug
    subdir_name   = fields.get("fqdn") or "DEV_custom_SAN"
    cust_sub_dir  = certs_dir / subdir_name

    certs_dir.mkdir(parents=True, exist_ok=True)

    if cust_sub_dir.exists():
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        cust_sub_dir.rename(Path(str(cust_sub_dir) + "-" + timestamp))
    cust_sub_dir.mkdir()

    subject  = parse_csr_subject(csr_text, cust_sub_dir)
    csr_file = cust_sub_dir / "csrFile.txt"  # already written by parse_csr_subject

    cert_filename, _ = DEVICE_TYPES.get(fields["gw_client"], ("GW_Client_Cert.txt", None))
    cert_file = cust_sub_dir / cert_filename
    cert_file.touch()

    san = build_san(fields)
    env = os.environ.copy()
    env["SAN"] = san

    subprocess.run(
        [
            OPENSSL, "ca",
            "-config", str(sub_ca_dir / "sub-ca.conf"),
            "-in",    str(csr_file),
            "-out",   str(cert_file),
            "-notext",
            "-extensions", "serverclient_ext",
            "-key",   ca_password,
            "-batch",
        ],
        env=env,
        check=False,
    )

    return cert_file, sub_ca_dir, root_ca_dir, subject


def print_pem_file(path, label):
    print(f"<h2>{e(label)}</h2>")
    print('<font color="#FF0000">')
    try:
        for line in Path(path).read_text().splitlines():
            print(f"{e(line)}<br>")
    except OSError as ex:
        print(f"<p>Error reading file: {e(ex)}</p>")
    print("</font>\n<p></p>")


def display_cert_results(cert_file, sub_ca_dir, root_ca_dir, subject, fields):
    print("<h2>Customer Details</h2>")
    print('<table width="80%">')
    print("  <tr>")
    print("    <th style='text-align:left'><u>What you entered</u></th>")
    print("    <th style='text-align:left'><u>What the CSR has</u></th>")
    print("  </tr>")
    print("  <tr>")
    print("    <td>")
    print(f"      Customer: {e(fields['customer'])}<br>")
    if fields["gw_client"] == "DEV":
        print(f"      Custom SAN: {e(fields.get('custom_san', ''))}<br>")
    else:
        if fields.get("fqdn"):
            print(f"      FQDN: {e(fields['fqdn'])}<br>")
        if fields.get("gw_svcs_fqdn"):
            print(f"      Gateway Services FQDN: {e(fields['gw_svcs_fqdn'])}<br>")
    print(f"      Device type: {e(fields['gw_client'])}<br>")
    print("    </td>")
    print("    <td>")
    print(f"      Country: {e(subject.get('country', ''))}<br>")
    print(f"      State: {e(subject.get('state', ''))}<br>")
    print(f"      Locale: {e(subject.get('locale', ''))}<br>")
    print(f"      Organization: {e(subject.get('org', ''))}<br>")
    print(f"      Org Unit: {e(subject.get('org_unit', ''))}<br>")
    print(f"      LHID / UUID: {e(subject.get('common_name', ''))}<br>")
    print("    </td>")
    print("  </tr>")
    print("</table>")
    print("<p></p>")

    print(f"""<form action="{CGI_SCRIPT}" method="get">
  <input type="hidden" name="f_liability" value="yes">
  <input type="submit" value="Make Another Cert!">
</form>
""")

    print("<h2>Certificate Details</h2>")
    print_pem_file(cert_file, f"Your {cert_file.name} is:")
    print_pem_file(sub_ca_dir / "sub-ca.crt", "Your I-CA.txt is:")
    print_pem_file(root_ca_dir / "root-ca.crt", "Your R-CA.txt is:")


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    emit_http_header()
    print(page_header())

    form     = cgi.FieldStorage()
    base_dir = Path(os.path.dirname(os.path.abspath(__file__)))

    csr_val       = (form.getvalue("f_csr") or "").strip()
    customer_val  = (form.getvalue("f_customer") or "").strip()
    liability_val = (form.getvalue("f_liability") or "").strip()

    if csr_val:
        fields = {
            "customer":     customer_val,
            "fqdn":         (form.getvalue("f_fqdn") or "").strip(),
            "gw_svcs_fqdn": (form.getvalue("f_gwSvcsFqdn") or "").strip(),
            "gw_client":    (form.getvalue("f_gwClient") or "").strip(),
            "custom_san":   (form.getvalue("f_custom_san") or "").strip(),
        }
        config = load_config()
        cert_file, sub_ca_dir, root_ca_dir, subject = generate_certificate(
            fields, csr_val, config, base_dir
        )
        display_cert_results(cert_file, sub_ca_dir, root_ca_dir, subject, fields)

    elif customer_val:
        fields = {
            "customer":     customer_val,
            "fqdn":         (form.getvalue("f_fqdn") or "").strip(),
            "gw_svcs_fqdn": (form.getvalue("f_gwSvcsFqdn") or "").strip(),
            "gw_client":    (form.getvalue("f_gwClient") or "").strip(),
            "custom_san":   (form.getvalue("f_custom_san") or "").strip(),
        }
        error = validate_fields(fields)
        if error:
            print(f"<p>{e(error)} Press Back to correct the form.</p>")
        else:
            show_csr_form(fields)

    elif liability_val:
        if liability_val == "no":
            print("<p>You must accept the Liability Notice before proceeding.</p>")
        else:
            show_customer_form()

    else:
        show_liability_form()

    print(page_footer())


if __name__ == "__main__":
    main()
