#!/usr/bin/perl -w

########################################################################
# Title: BlackRidge Certificate Generator
# Author: Doug Johnson - dj@blackridge.us
# Modified by: Steve Hershman II - shershman@blackridge.us [20170804]
# Version: 4.0
# Assumptions:
#   1) Running on Centos 7
#   2) Root CA is installed in /var/www/cgi-bin/certs/root-ca
#   3) Subordinate CA is installed in /var/www/cgi-bin/certs/sub-ca
#   4) OpenSSL has been upgraded to latest version
#     A) yum upgrade openssl
#
# Set Up Instructions:
#   1) Deploy Apache
#     A) yum install httpd
#     B) systemctl start httpd
#     C) systemctl enable httpd
#     D) firewall-cmd --permanent --add-port=80/tcp
#     E) firewall-cmd --permanent --add-port=443/tcp
#     F) firewall-cmd --reload
#   2) Update OpenSSL
#     A) yum update openssl
#   3) Make sure the apache can write to the cgi-bin directory
#     A) sudo chmod -R 777 /usr/local/cgi-bin - yes we know this is bad
#     B) sudo chown -R apache /var/www/cgi-bin
#     C) sudo chgrp -R apache /var/www/cgi-bin
#   4) Disable SELinux
#     A) edit /etc/sysconfig/selinux
#     B) set SELINUX=disabled
#     C) restart the centos server
#
# Testing Parameters
#   1) ./BR_Cert_Gen.cgi f_liability=yes
#   2) ./BR_Cert_Gen.cgi f_liability=yes f_customer=TheHorde f_fqdn=undercity.thehorde f_hostname=undercity f_ipAddress=192.168.1.210 f_gwClient=gateway
#   3) ./BR_Cert_Gen.cgi f_liability=yes f_customer=TheHorde f_fqdn=undercity.thehorde f_hostname=undercity f_ipAddress=192.168.1.210 f_gwClient=gateway f_csr=12345
#
########################################################################

use Time::Local;
use POSIX qw(strftime);
use strict;
use CGI qw(:all);
use DBI;
#use BRCA;

#############################################################
# Environment Variables
#############################################################
my $cgi_script = "\/cgi-bin\/BR_Cert_Gen4.cgi";
my $echo = "/usr/bin/echo";
my $touch = "/usr/bin/touch";
my $mkdir = "/usr/bin/mkdir";
my $server = 'localhost';
#SH2 my $port = '3307';
my $db = 'certificates';
#SH2 my $db = 'certificates_sha256';
my $username = 'certmgr';
my $password = 'sw181da';
#my $dbh = DBI->connect("dbi:mysql:$db:$server", $username, $password);


#############################################################
# Time Variables
#############################################################
my @c_time = (localtime);
my $currenttime = timelocal(@c_time);
my $currentdate = strftime "%d%b%Y", @c_time;
my $now = strftime "%Y-%m-%d %H:%M:%S", @c_time;

#############################################################
# Global Variables
#############################################################
my $rootCaDir="/var/www/cgi-bin/certs/root-ca";
my $subCaDir="/var/www/cgi-bin/certs/sub-ca";
my $subCaConfig="sub-ca.conf";
my $acceptLiability;
my $customer;
my $fqdn;
my $hostname;
my $ipAddress;
my $gwSvcsFqdn;
my $gwSvcsIpAddress;
my $sanFqdns;
my $sanIps;
my $gwClient;
my $csr;
my $csrFile;
my $csrCountry;
my $csrState;
my $csrLocale;
my $csrOrg;
my $csrOrgUnit;
my $csrCommonName;
my $csrOrgNoSpaces = "";
my $csrOrgUnitNoSpaces = "";

#############################################################
# Subroutines
#############################################################
sub db_escape{
  my ( $string ) = @_;
  $string =~ s/\\/\\\\/g;
  $string =~ s/'/\\'/g;
  $string =~ s/-/\\-/g;
  $string =~ s/\./\\./g;
  return ( $string );
} # End of db_escape

sub whack_a_space{
  my ( $string ) = @_;
  $string =~ s/ //g;
  return ( $string );
} # End of whack_a_space

sub acceptLiability{
  print "<h2><center>Liability Notice</center></h2>\n";

  print "<p>The BlackRidge software uses certificates to identify various BlackRidge Technology internal system components, providing both authentication and encryption. The BlackRidge solution will not function without this level of operational security being in place.</p>\n";

  print "<p>These certificates are currently generated by a certificate authority (CA) provided and hosted by BlackRidge Technology. BlackRidge Technology is transitioning from providing and hosting the CA to using a recognized certificate provider and certificate authority. When this transition is complete new certificates will be issued to all existing customers. There will be no additional charge to any customer to upgrade their certificates.</p>\n";

  print "<p>BlackRidge Technology does not accept any liability associated with using internally generated certificates, including any liability associated by providing certificate authority services to customers. Should a customer have  their own certificate authority that they would like to use with the BlackRidge solution the software supports this today.</p>\n";

  print "<p></p>\n";

  print "<p>Do you understand this liability notice and, if this is for a customer deployment, have you explained this to them so that they accept it?</p>\n";

  print "<form action=\"$cgi_script\" method=\"post\">\n";
  print "<table>\n";

  print "<tr>\n";
  print "<td>Do you accept?</td>\n";
  print "<td><select name=f_liability><option selected value=\"\">Select a Response\n";
  print "  <option value=\"yes\">Yes\n";
  print "  <option value=\"no\">No\n";
  print "  </select></td>\n";
  print "</tr>\n";

  print "</table>\n";

  print "<p></p>\n";

  print "<font color=\"black\"><input type=submit value=\"Submit\"></font>\n";
  print "</form>\n";
}

sub getCustomerInfo{
  print "Please provide the following information:\n";

  print "<p></p>\n";

  print "<form action=\"$cgi_script\" method=\"post\">\n";
  print "<table>\n";

    print "<tr>\n";
    print "<td>Customer Name:</td>\n";
    print "<td><font color=\"black\"><input type=text name=f_customer value=\"\"></font></td>\n";
    print "<td><i>Do not put any spaces.  The tool will not break and your certificate will be generated but not displayed to you.</i></td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td>Fully Qualified Domain Name:</td>\n";
    print "<td><font color=\"black\"><input type=text name=f_fqdn value=\"\"></font></td>\n";
    print "<td><i>If there is no FQDN just put hostname.customer here.</i></td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td>Hostname:</td>\n";
    print "<td><font color=\"black\"><input type=text name=f_hostname value=\"\"></font></td>\n";
    print "<td><i>If you leave this blank the entire form will reset.</i></td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td>IP Address:</td>\n";
    print "<td><font color=\"black\"><input type=text name=f_ipAddress value=\"\"></font></td>\n";
    print "<td><i>There is no address validation. Be sure you type this correctly. Use the Management IP for Gateways.</i></td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td>Gateway Services FQDN:</td>\n";
    print "<td><font color=\"black\"><input type=text name=f_gwSvcsFqdn value=\"\"></font></td>\n";
    print "<td><i><b>***GATEWAYS ONLY***</b> No spaces here as well. Be sure you type this correctly.</i></td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td>Gateway Services IP Address:</td>\n";
    print "<td><font color=\"black\"><input type=text name=f_gwSvcsIpAddress value=\"\"></font></td>\n";
    print "<td><i><b>***GATEWAYS ONLY***</b> There is no address validation. Be sure you type this correctly.</i></td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td>Is this request for a Gateway or a Client?</td>\n";
    print "<td><select name=f_gwClient><option selected value=\"\">Select a Response\n";
    print "  <option value=\"gateway\">Gateway\n";
    print "  <option value=\"bem\">BEM\n";
    print "  <option value=\"addia\">Active Directory DIA\n";
    print "  <option value=\"trustlevel\">Trust Level\n";
    print "  <option value=\"endpoint\">Endpoint Client\n";
    #print "  <option value=\"client\">Client\n";
    print "  </select></td>\n";
    print "<td><i>AD DIA, Trust Level, and Endpoint Client are clients.</i></td>\n";
    print "</tr>\n";

  print "</table>\n";

  print "<p></p>\n";

  print "<font color=\"black\"><input type=submit value=\"Submit\"></font>\n";
}

print header();
print start_html("BlackRidge Certificate Generation - for TAC 4.1+ ONLY");

#print "<link rel=\"stylesheet\"\n";
#print "\ttype=\"text/css\"\n";
#print "\thref=\"../bootstrap.css\"\n";
#print "/>\n\n";

print "<link rel=\"stylesheet\"\n";
print "\ttype=\"text/css\"\n";
print "\thref=\"../styles.css\"\n";
print "/>\n\n";


print "<h1><center>BlackRidge Certificate Generation</center></h1>\n";
print "<h2><font color=\"red\"><center>***For use with TAC 4.1 and beyond ONLY***</center></font></h2>\n";

if(param( 'f_csr' ))
{
  $csr = param( 'f_csr');
  $customer = param( 'f_customer');
  $fqdn = param( 'f_fqdn');
  $hostname = param( 'f_hostname');
  $ipAddress = param( 'f_ipAddress');
  $gwSvcsFqdn = param( 'f_gwSvcsFqdn');
  $gwSvcsIpAddress = param( 'f_gwSvcsIpAddress');
  $gwClient = param( 'f_gwClient');

  if ($csr eq '')
  {
    print "Sorry, you have to enter a CSR.  You can press the back button in your browser to correct this.\n";
  }
  else
  {
    my $certsDir = "certs";

    if (!-d $certsDir)
    {
	mkdir $certsDir, 0777 or die "Unable to create $certsDir - $!\n";
    }

    ##########################################################################
    # Create temporary CSR file to extract info from before moving into
    # customer directory
    ##########################################################################
    #my $tmpCsrFile = "/tmp/csrFile.txt";
    my $tmpCsrFile = "tmpCsrFile.txt";
    open (TMPCSRFILE, "> $tmpCsrFile") or die "Unable to open $tmpCsrFile for writing $!\n";
    print TMPCSRFILE $csr;
    close TMPCSRFILE;

    my $tmpCsrDecode = "tmpCsrFileDecode.txt"; 
    my $openSslDecode = "openssl req -in $tmpCsrFile -noout -text > $tmpCsrDecode"; 
    system ($openSslDecode);

    open(CSR_DECODE,"<$tmpCsrDecode");

    while(my $line = <CSR_DECODE>)
    {
      chomp ($line);
      if ($line =~ m/^\s*Subject: C=(.*), ST=(.*), L=(.*), O=(.*), OU=(.*), CN=(.*)/i)
      #if ($line =~ m/^\s*Subject: CN=(.*), C=(.*), ST=(.*), L=(.*), O=(.*), OU=(.*)
      {
        $csrCountry = $1;
        $csrState = $2;
        $csrLocale = $3;
        $csrOrg = $4;
        $csrOrgUnit = $5;
        $csrCommonName = $6;
      }
    }

    #########################
    # DJ Debug
    #########################
    #print "$csrOrg\n";
    #print "$csrOrgUnit\n";
    #########################
    # DJ Debug
    #########################

    #($csrOrgNoSpaces = $csrOrg) =~s/\s*//g;
    #($csrOrgUnitNoSpaces = $csrOrgUnit) =~s/\s*//g;
    
    my $customerNoSpaces = whack_a_space($customer);

    my $customerDir = "$certsDir/customers/$customerNoSpaces";
    #my $customerDir = "$certsDir/$csrOrgNoSpaces/$csrOrgUnitNoSpaces";

    my $custSubDir = $customerDir . "/" . $hostname . "_" . $ipAddress;
    #my $custSubDir = $customerDir . "/" . $csrCommonName;

    my $csrFile = $custSubDir . "/csrFile.txt";

    if (!-d $customerDir)
    {
	mkdir $customerDir, 0777 or die "Unable to create $customerDir - $!\n";
    }

    if (!-d $custSubDir)
    {
	mkdir $custSubDir, 0777 or die "Unable to create $custSubDir - $!\n";
    }
    else
    {
        # We are using seconds in the rename for jerks who want to try to break the tool
        my $newDirectory = $custSubDir . "-" . $now;
        rename $custSubDir,$newDirectory;
	    mkdir $custSubDir, 0777 or die "Unable to create $custSubDir - $!\n";
    }

    open (CSRFILE, "> $csrFile") or die "Unable to open $csrFile for writing $!\n";
    print CSRFILE $csr;
    close CSRFILE;

    #########################################################
    # Start of certificate generation output 
    #########################################################
    print "<h2>Customer Details</h2>";

    print "<table width=\"80%\">\n";
    print "<tr>\n";
    print "<td><u><b>What you entered</b></u></td>\n";
    print "<td><u><b>What the CSR has</b></u></td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td>\n";
    print "Customer: $customer<br>\n";
    print "FQDN: $fqdn<br>\n";
    print "Hostname: $hostname<br>\n";
    print "MGMT IP Address: $ipAddress<br>\n";
    print "Gateway Services FQDN: $gwSvcsFqdn<br>\n";
    print "Gateway Services IP Address: $gwSvcsIpAddress<br>\n";
    print "Gateway or Client: $gwClient<br>\n";
    print "</td>\n";

    print "<td>\n";
    print "Country: $csrCountry<br>\n";
    print "State: $csrState<br>\n";
    print "Locale: $csrLocale<br>\n";
    print "Organization: $csrOrg<br>\n";
    print "Org Unit: $csrOrgUnit<br>\n";
    print "LHID / UUID: $csrCommonName<br>\n";
    print "</td>\n";

    print "</tr>\n";
    print "</table>\n";
    print "<p></p>\n";

#SH2 - added button to restart the process for another cert

    print "<form action=\"$cgi_script\" method=\"get\">\n";
    print "<input type=\"hidden\" name=\"f_liability\" value=\"yes\">\n";
    print "<input type=submit value=\"Make Another Cert!\">\n";
    print "</form>\n";

    #########################################################
    # Start of certificate generation
    #########################################################

    my $certFile;
    my @certGenCmd;
    my $envCommand;

    my $command;

    if($gwClient eq "gateway")
    {
#SH2 - if $gwSvcsIpAddress is set, add it to the SAN; otherwise use only MGMT IP
      if ($gwSvcsIpAddress eq "")
      {
          $sanIps = "IP:$ipAddress";
      } 
      else
      {
          $sanIps = "IP:$ipAddress,IP:$gwSvcsIpAddress";
      }
#SH2 - if $gwSvcsFqdn is set, add it to the SAN; otherwise use only MGMT FQDN
      if ($gwSvcsFqdn eq "")
      {
          $sanFqdns = "DNS:$fqdn";
      } 
      else
      {
          $sanFqdns = "DNS:$fqdn,DNS:$gwSvcsFqdn";
      }

#      $ENV{SAN}="DNS:$fqdn,DNS:$hostname,$sanIps";
      $ENV{SAN}="$sanFqdns,DNS:$hostname,$sanIps,URI:blackridge://$fqdn/Agent/userInterface";
      $envCommand = "export $ENV{SAN}";

      #$certFile = $customerDir . "/GW_Cert.txt";
      $certFile = "GW_Cert.txt";
      open (CERTFILE, "> $custSubDir/$certFile") or die "Unable to open $certFile for writing $!\n";
      close CERTFILE;
      #@certGenCmd = qw('/usr/bin/openssl ca -config certs/sub-ca/sub-ca.conf -in $csrFile -out $certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch');
      
      #$certGenCmd[3] = "certs/sub-ca/$subCaConfig";
      #$certGenCmd[5] = "$csrFile";
      #$certGenCmd[7] = "$certFile";
      $command = "/usr/bin/openssl ca -config $subCaDir/sub-ca.conf -in $csrFile -out $custSubDir/$certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch";
    }
    elsif($gwClient eq "addia")
    {
      $ENV{SAN}="DNS:$fqdn,DNS:$hostname,IP:$ipAddress,URI:blackridge://$fqdn/Agent/identityInsertion";
      $envCommand = "export $ENV{SAN}";
      #$certFile = $customerDir . "/GW_Cert.txt";
      $certFile = "GW_Cert.txt";
      #$certFile = "ADDIA_Cert.txt";
      open (CERTFILE, "> $custSubDir/$certFile") or die "Unable to open $certFile for writing $!\n";
      close CERTFILE;
      #@certGenCmd = qw('/usr/bin/openssl ca -config certs/sub-ca/sub-ca.conf -in $csrFile -out $certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch');
      
      #$certGenCmd[3] = "certs/sub-ca/$subCaConfig";
      #$certGenCmd[5] = "$csrFile";
      #$certGenCmd[7] = "$certFile";
      $command = "/usr/bin/openssl ca -config $subCaDir/sub-ca.conf -in $csrFile -out $custSubDir/$certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch";
    }
    elsif($gwClient eq "bem")
    {
      $ENV{SAN}="DNS:$fqdn,DNS:$hostname,IP:$ipAddress,URI:blackridge://$fqdn/Agent/userInterface";
      $envCommand = "export $ENV{SAN}";

      #$certFile = $customerDir . "/GW_Cert.txt";
      #$certFile = "GW_Cert.txt";
      $certFile = "BEM_Cert.txt";
      open (CERTFILE, "> $custSubDir/$certFile") or die "Unable to open $certFile for writing $!\n";
      close CERTFILE;
      #@certGenCmd = qw('/usr/bin/openssl ca -config certs/sub-ca/sub-ca.conf -in $csrFile -out $certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch');
      
      #$certGenCmd[3] = "certs/sub-ca/$subCaConfig";
      #$certGenCmd[5] = "$csrFile";
      #$certGenCmd[7] = "$certFile";
      $command = "/usr/bin/openssl ca -config $subCaDir/sub-ca.conf -in $csrFile -out $custSubDir/$certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch";
    }
    elsif($gwClient eq "trustlevel")
    {
      $ENV{SAN}="DNS:$fqdn,DNS:$hostname,IP:$ipAddress,URI:blackridge://$fqdn/Agent/trustLevel";
	      $envCommand = "export $ENV{SAN}";

	      #$certFile = $customerDir . "/GW_Cert.txt";
	      $certFile = "GW_Cert.txt";
	      #$certFile = "TrustLevel_Cert.txt";
	      open (CERTFILE, "> $custSubDir/$certFile") or die "Unable to open $certFile for writing $!\n";
	      close CERTFILE;
	      #@certGenCmd = qw('/usr/bin/openssl ca -config certs/sub-ca/sub-ca.conf -in $csrFile -out $certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch');
	      
	      #$certGenCmd[3] = "certs/sub-ca/$subCaConfig";
	      #$certGenCmd[5] = "$csrFile";
	      #$certGenCmd[7] = "$certFile";
	      $command = "/usr/bin/openssl ca -config $subCaDir/sub-ca.conf -in $csrFile -out $custSubDir/$certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch";
    }
    elsif($gwClient eq "endpoint")
    {
      $ENV{SAN}="DNS:$fqdn,DNS:$hostname,IP:$ipAddress,URI:blackridge://$fqdn/Agent/identityActivation";
	      $envCommand = "export $ENV{SAN}";

	      #$certFile = $customerDir . "/GW_Cert.txt";
	      $certFile = "Endpoint_Client.txt";
	      open (CERTFILE, "> $custSubDir/$certFile") or die "Unable to open $certFile for writing $!\n";
	      close CERTFILE;
	      
	      $command = "/usr/bin/openssl ca -config $subCaDir/sub-ca.conf -in $csrFile -out $custSubDir/$certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch";
    }
    else
    {
      #$certFile = $customerDir . "/GW_Client_Cert.txt";
      $certFile = "GW_Client_Cert.txt";
      open (CERTFILE, "> $custSubDir/$certFile") or die "Unable to open $certFile for writing $!\n";
      close CERTFILE;
      #@certGenCmd = qw(/usr/bin/openssl ca -config certs/sub-ca/sub-ca.conf -in $csrFile -out $certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch);
      #$certGenCmd[3] = "certs/sub-ca/$subCaConfig";
      #$certGenCmd[5] = "$csrFile";
      #$certGenCmd[7] = "$certFile";
      $command = "/usr/bin/openssl ca -config $subCaDir/sub-ca.conf -in $csrFile -out $custSubDir/$certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch";
    }

    system ($envCommand);
    system ($command);
    #system @certGenCmd;

    print "<h2>Certificate Details</h2>";

#########
# DJ Debug
#########
#print "Debug stuff<br>\n";
#print "The certificate file is <a href=\"$custSubDir/$certFile\">Here</a><br>\n";
#print "The CA chain file is <a href=\"certificate_trust_chain.txt\">Here</a><br>\n";
#print "End debug stuff<br>\n";
#########
# DJ Debug
#########

    print "<b>Your $certFile is:</b><br>\n";
    print "<font color=\"#FF0000\">\n";
    open (CERTFILE, "$custSubDir/$certFile") or die "Unable to open $certFile for reading $!\n";
    while (<CERTFILE>)
    {
      chomp;
      print "$_<br>\n";
    }
    close(CERTFILE);
    print "</font>\n";

    print "<p></p>\n";

    print "<b>Your I-CA.txt is:</b><br>\n";
    print "<font color=\"#FF0000\">\n";
    open (SUBCACRT, "$subCaDir/sub-ca.crt") or die "Unable to open sub-ca.crt for reading $!\n";
    while (<SUBCACRT>)
    {
      chomp;
      print "$_<br>\n";
    }
    close(SUBCACRT);
    print "</font>\n";

    print "<p></p>\n";

    print "<b>Your R-CA.txt is:</b><br>\n";
    print "<font color=\"#FF0000\">\n";
    open (ROOTCACRT, "$rootCaDir/root-ca.crt") or die "Unable to open root-ca.crt for reading $!\n";
    while (<ROOTCACRT>)
    {
      chomp;
      print "$_<br>\n";
    }
    close(ROOTCACRT);

    #system('$mkdir -p /certs/$customer');
    #system('$echo $csr > /certs/$customer/csrFile.txt');

    #open(CSRFILE,">/certs/$customer/csrFile.txt");

    #print CSRFILE $csr;
  
    ###############################
    # Write Julia's Report File
    ###############################
#SH2    updateTrackingReport();
#SH2    updateTrackingDB();
  }
}
elsif(param('f_hostname'))
{ # Begin - section to get CSR
  $customer = param('f_customer');
  $fqdn = param('f_fqdn');
  $hostname = param('f_hostname');
  $ipAddress = param('f_ipAddress');
  $gwSvcsFqdn = param('f_gwSvcsFqdn');
  $gwSvcsIpAddress = param('f_gwSvcsIpAddress');
  $gwClient = param('f_gwClient');

  if ( ($customer eq '') or ($fqdn eq '')  or ($hostname eq '') or ($ipAddress eq '')  or ($gwClient eq '') )
  {
    print "Sorry, you have to enter all information.  You can press the back button in your browser to correct this.\n";
  }
  else
  {
    print "<h2>Customer Details</h2>";
    print "Customer is $customer<br>\n";
    print "FQDN is $fqdn<br>\n";
    print "Hostname is $hostname<br>\n";
    print "MGMT IP Address is $ipAddress<br>\n";
    print "Gateway Services FQDN is $gwSvcsFqdn<br>\n";
    print "Gateway Services IP Address is $gwSvcsIpAddress<br>\n";
    print "Gateway or Client is $gwClient<br>\n";

    print "<p></p>\n";

    print "Paste CSR here...<br>\n";

    print "<font color=\"black\">\n";
    print "<form action=\"$cgi_script\" method=\"post\">\n";
    print "<table>\n";

      print "<tr>\n";
      print "<td><textarea rows=30 cols=78 name=f_csr></textarea></td>\n";
      print "</tr>\n";

    print "</table>\n";

    print "<p></p>\n";

    print "<input type=hidden name=f_customer value=\"$customer\">\n";
    print "<input type=hidden name=f_fqdn value=\"$fqdn\">\n";
    print "<input type=hidden name=f_hostname value=\"$hostname\">\n";
    print "<input type=hidden name=f_ipAddress value=\"$ipAddress\">\n";
    print "<input type=hidden name=f_gwSvcsFqdn value=\"$gwSvcsFqdn\">\n";
    print "<input type=hidden name=f_gwSvcsIpAddress value=\"$gwSvcsIpAddress\">\n";
    print "<input type=hidden name=f_gwClient value=\"$gwClient\">\n";

    print "<input type=submit value=\"Submit\">\n";
    print "</form>\n";
    print "</font>\n";

  }
} # End - section to get CSR
elsif(param( 'f_liability' ))
{
  $acceptLiability = param( 'f_liability');

  if ($acceptLiability eq 'no')
  {
    print "Sorry but you must accept the Liability Notice before proceeding.  Each time.  Every time.  We are tracking you.\n";
  }
  else
  {
    getCustomerInfo();
  }
}
else 
{
  acceptLiability();
}

print end_html();
