package BRCA;
use Time::Local;
use POSIX qw(strftime);
use strict;
use CGI qw(:all);


my $Version = 1.00;
my @ISA = qw(Exporter);

#############################################################
# Subroutines
#############################################################
sub acceptLiability{
  print "<h2><center>Liability Notice</center></h2>\n";

  print "<p>The BlackRidge software release 2.3.0 uses certificates to identify various BlackRidge Technology internal system components.  These certificates are generated by a certificate authority (CA) provided and hosted by BlackRidge Technology.</p>\n";

  print "<p>BlackRidge Technology is transitioning from providing and hosting the CA to using a recognized certificate provider and certificate authority.  This is expected to occur in Q1 2016 and will be accompanied by a new BlackRidge software release, 2.3.1.  When software release 2.3.1 is available, all users of software release 2.3.0 should upgrade.  Software release 2.3.1 will be provided to users of 2.3.0 at no additional charge.</p>\n";

  print "<p>BlackRidge Technology does not accept any liability associated with using software release 2.3.0, including any liability associated to providing certificate authority services to customers using BlackRidge software release 2.3.0.</p>\n";
  print "<p></p>\n";


  print "<p>Do you understand this liability notice and, if this is for a customer deployment, have you explained this to them so that they accept it?</p>\n";

  print "<form action=\"$cgi_script\" method=\"post\">\n";
  print "<table>\n";

  print "<tr>\n";
  print "<td>Do you accept?</td>\n";
  print "<td><select name=f_liability><option selected value=\"\">Select a Response\n";
  print "  <option value=\"yes\">Yes\n";
  print "  <option value=\"no\">No\n";
  print "  </select></td>\n";
  print "</tr>\n";

  print "</table>\n";

  print "<p></p>\n";

  print "<font color=\"black\"><input type=submit value=\"Submit\"></font>\n";
  print "</form>\n";
}

sub getCustomerInfo{
  print "Please provide the following information:\n";

  print "<p></p>\n";

  print "<form action=\"$cgi_script\" method=\"post\">\n";
  print "<table>\n";

    print "<tr>\n";
    print "<td>Customer Name:</td>\n";
    print "<td><font color=\"black\"><input type=text name=f_customer value=\"\"></font></td>\n";
    print "<td><i>Do not put any spaces.  The tool will not break and your certificate will be generated but not displayed to you.</i></td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td>Fully Qualified Domain Name:</td>\n";
    print "<td><font color=\"black\"><input type=text name=f_fqdn value=\"\"></font></td>\n";
    print "<td><i>If there is no FQDN just put hostname.customer here.</i></td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td>Hostname:</td>\n";
    print "<td><font color=\"black\"><input type=text name=f_hostname value=\"\"></font></td>\n";
    print "<td><i>If you leave this blank the entire form will reset.</i></td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td>IP Address:</td>\n";
    print "<td><font color=\"black\"><input type=text name=f_ipAddress value=\"\"></font></td>\n";
    print "<td><i>There is no address validation. Be sure you type this correctly.</i></td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td>Is this request for a Gateway or a Client?</td>\n";
    print "<td><select name=f_gwClient><option selected value=\"\">Select a Response\n";
    print "  <option value=\"gateway\">Gateway\n";
    print "  <option value=\"client\">Client\n";
    print "  </select></td>\n";
    print "<td><i>Dyanic AD Agent is a client.</i></td>\n";
    print "</tr>\n";

  print "</table>\n";

  print "<p></p>\n";

  print "<font color=\"black\"><input type=submit value=\"Submit\"></font>\n";
}

