A#!/usr/bin/perl -w

########################################################################
# Title: Inisinet Certificate Generator
# Author: Doug Johnson - doug.johnson@invisinet.com
# Version: 6.0
# Assumptions:
#   1) Running on Centos 7
#   2) Root CA is installed in /var/www/cgi-bin/certs/root-ca
#   3) Subordinate CA is installed in /var/www/cgi-bin/certs/sub-ca
#   4) OpenSSL has been upgraded to latest version
#     A) yum upgrade openssl
#
# Set Up Instructions:
#   1) Deploy Apache
#     A) yum install httpd
#     B) systemctl start httpd
#     C) systemctl enable httpd
#     D) firewall-cmd --permanent --add-port=80/tcp
#     E) firewall-cmd --permanent --add-port=443/tcp
#     F) firewall-cmd --reload
#   2) Update OpenSSL
#     A) yum update openssl
#   3) Make sure the apache can write to the cgi-bin directory
#     A) sudo chmod -R 777 /usr/local/cgi-bin - yes we know this is bad
#     B) sudo chown -R apache /var/www/cgi-bin
#     C) sudo chgrp -R apache /var/www/cgi-bin
#   4) Disable SELinux
#     A) edit /etc/sysconfig/selinux
#     B) set SELINUX=disabled
#     C) restart the centos server
#
# Testing Parameters
#   1) ./IV_Cert_Gen.cgi f_liability=yes
#   2) ./IV_Cert_Gen.cgi f_liability=yes f_customer=TheHorde f_fqdn=undercity.thehorde f_hostname=undercity f_ipAddress=192.168.1.210 f_gwClient=gateway
#   3) ./IV_Cert_Gen.cgi f_liability=yes f_customer=TheHorde f_fqdn=undercity.thehorde f_hostname=undercity f_ipAddress=192.168.1.210 f_gwClient=gateway f_csr=12345
#
########################################################################

use Time::Local;
use POSIX qw(strftime);
use strict;
use CGI qw(:all);
use DBI;
#use BRCA;

#############################################################
# Environment Variables
#############################################################
my $cgi_script = "\/cgi-bin\/IV_Cert_Gen.cgi";
my $echo = "/usr/bin/echo";
my $touch = "/usr/bin/touch";
my $mkdir = "/usr/bin/mkdir";
my $server = 'localhost';
#SH2 my $port = '3307';
my $db = 'certificates';
my $username = 'certmgr';
my $password = 'REDACTED';
#my $dbh = DBI->connect("dbi:mysql:$db:$server", $username, $password);
#SH2 my $dbh = DBI->connect("dbi:mysql:database=$db;host=$server;port=$port;mysql_read_default_file=/etc/mysql/my.cnf", $username, $password);


#############################################################
# Time Variables
#############################################################
my @c_time = (localtime);
my $currenttime = timelocal(@c_time);
my $currentdate = strftime "%d%b%Y", @c_time;
my $now = strftime "%Y-%m-%d %H:%M:%S", @c_time;

#############################################################
# Global Variables
#############################################################
my $rootCaDir="/var/www/cgi-bin/certs/root-ca";
my $subCaDir="/var/www/cgi-bin/certs/sub-ca";
my $subCaConfig="sub-ca.conf";
my $acceptLiability;
my $customer;
my $fqdn;
my $hostname;
my $ipAddress;
my $gwSvcsFqdn;
my $gwSvcsIpAddress;
my @sanFqdns;
my @sanIps;
my $gwClient;
my $csr;
my $csrFile;
my $csrCountry;
my $csrState;
my $csrLocale;
my $csrOrg;
my $csrOrgUnit;
my $csrCommonName;
my $csrOrgNoSpaces = "";
my $csrOrgUnitNoSpaces = "";
my $custom_san;

#############################################################
# Subroutines
#############################################################
sub db_escape{
  my ( $string ) = @_;
  $string =~ s/\\/\\\\/g;
  $string =~ s/'/\\'/g;
  $string =~ s/-/\\-/g;
  $string =~ s/\./\\./g;
  return ( $string );
} # End of db_escape

sub whack_a_space{
  my ( $string ) = @_;
  $string =~ s/ //g;
  return ( $string );
} # End of whack_a_space

sub acceptLiability{
  print "<h2><center>Liability Notice</center></h2>\n";

  print "<p>The <Company> software uses certificates to identify various <Company> internal system components, providing both authentication and encryption. The <Company> solution will not function without this level of operational security being in place.</p>\n";

  print "<p>These certificates are currently generated by a certificate authority (CA) provided and hosted by <Company>. <Company> is transitioning from providing and hosting the CA to using a recognized certificate provider and certificate authority. When this transition is complete new certificates will be issued to all existing customers. There will be no additional charge to any customer to upgrade their certificates.</p>\n";

  print "<p><Company> does not accept any liability associated with using internally generated certificates, including any liability associated by providing certificate authority services to customers. Should a customer have  their own certificate authority that they would like to use with the <Company> solution the software supports this today.</p>\n";

  print "<p></p>\n";

  print "<p>Do you understand this liability notice and, if this is for a customer deployment, have you explained this to them so that they accept it?</p>\n";

  print "<form action=\"$cgi_script\" method=\"post\">\n";
  print "<table>\n";

  print "<tr>\n";
  print "<td>Do you accept?</td>\n";
  print "<td><select name=f_liability>";
  print "<option selected value=\"\">Select a Response\n";
  print "  <option value=\"yes\">Yes\n";
  print "  <option value=\"no\">No\n";
  print "  </select></td>\n";
  print "</tr>\n";

  print "</table>\n";

  print "<p></p>\n";

  print "<font color=\"black\"><input type=submit value=\"Submit\"></font>\n";
  print "</form>\n";
}

sub getCustomerInfo{
  print "Please provide the following information:\n";

  print "<p></p>\n";

  print "<form action=\"$cgi_script\" method=\"post\">\n";
  print q{
  <script>
    function handleSelect(entity) {
      var row_customer = '<tr>' +
        '<td>Customer Name:</td>' +
        '<td><font color="black"><input type=text name=f_customer value=""></font></td>' +
        '<td><i>Do not put any spaces.  The tool will not break and your certificate will be generated but not displayed to you.</i></td>' +
        '</tr>';

      var row_fqdn = '<tr>' +
        '<td>Fully Qualified Domain Name:</td>' +
        '<td><font color="black"><input type=text name=f_fqdn value=""></font></td>' +
        '<td><i>If there is no FQDN just put hostname.customer here.</i></td>' +
        '</tr>';

      var row_gwsvc_fqdn = '<tr>' +
        '<td>Gateway Services FQDN:</td>' +
        '<td><font color="black"><input type=text name=f_gwSvcsFqdn value=""></font></td>' +
        '<td><i><b>***GATEWAYS ONLY***</b> No spaces here as well. Be sure you type this correctly.</i></td>' +
        '</tr>';

      var row_custom_san = '<tr>' + 
        '<td>Custom SAN:</td>' +
        '<td colspan="2"><font color="black"><input type=text name=f_custom_san value=""></font></td>' +
        '</tr>';

      var row_spacer = '<tr><td colspan="3"><br/><br/></td></tr>';

      var table_contents = "";

      var san_help_empty = ''

      var san_help = `
  <br>
  <table>  
  <th>Supported SAN Tags</th>  
  <tr><td>DNS</td><td>for FQDN or hostname</td></tr>  
  <tr><td>IP</td><td>for IPv4 or IPv6</td></tr>  
  <tr><td>URI</td><td>for Certificate Group</td></tr>  
  </table>  
  <br>  
  Tags and values are separated by the colon (:) character, e.g.  
  <br>  
  <pre>  
      DNS<b>:</b>blackridge.example.com  
  </pre>  
  Separate entries are separated by the comma (,) character, e.g.  
  <pre>  
      DNS:blackridge.example.com<b>,</b>IP:1.1.1.1  
  </pre>  
  You may input as many DNS or IP fields as needed.  
  <br><br>  
  You may mix DNS and IP fields, as well as FQDNs, hostnames, IPv4 and IPv6 addresses as needed.  
  <br><br>  
  One and only one URI field should be added to the SAN.  
  <pre>  
DNS:blackridge.example.com<b>,</b>IP:1.1.1.1,<b>URI:blackridge://blackridge.example.com/Agent/userInterface</b>
  </pre>
  <table>
    <th align=\"left\">Examples</th>
    <tr><td>Gateway, FQDNs only</td><td>DNS:blackridge.example.com,DNS:br-activ.example.com,URI:blackridge://blackridge.example.com/Agent/userInterface</td></tr>
    <tr><td>Gateway, FQDNs and IPs</td><td>DNS:blackridge.example.com,IP:1.1.1.1,DNS:br-activ.example.com,IP:2.2.2.2,URI:blackridge://blackridge.example.com/Agent/userInterface</td></tr>
  <tr><td>BEM, FQDNs only</td><td>DNS:blackridge.example.com,URI:blackridge://blackridge.example.com/Agent/userInterface</td></tr>
  <tr><td>AD Agent</td><td>DNS:blackridge.example.com,URI:blackridge://blackridge.example.com/Agent/identityInsertion</td></tr>  
  <tr><td>Endpoint</td><td>DNS:blackridge.example.com,URI:blackridge://blackridge.example.com/Agent/identityActivation</td></tr> 
  <tr><td>Trust Level</td><td>DNS:blackridge.example.com,URI:blackridge://blackridge.example.com/Agent/trustlevel</td></tr>
  </table>  
`;

      switch(entity)
      {
        case "gateway":
          table_contents = row_customer + row_spacer + row_fqdn + row_spacer + row_gwsvc_fqdn;
          document.getElementById("myTableContainer").innerHTML = table_contents;
          document.getElementById("mySANHelp").innerHTML = san_help_empty;
        break;
        case "bem":
          table_contents = row_customer + row_spacer + row_fqdn;
          document.getElementById("myTableContainer").innerHTML = table_contents;
          document.getElementById("mySANHelp").innerHTML = san_help_empty;
        break;
        case "addia":
          table_contents = row_customer + row_spacer + row_fqdn;
          document.getElementById("myTableContainer").innerHTML = table_contents;
          document.getElementById("mySANHelp").innerHTML = san_help_empty;
        break;
        case "trustlevel":
          table_contents = row_customer + row_spacer + row_fqdn;
          document.getElementById("myTableContainer").innerHTML = table_contents;
          document.getElementById("mySANHelp").innerHTML = san_help_empty;
        break;
        case "endpoint":
          table_contents = row_customer + row_spacer + row_fqdn;
          document.getElementById("myTableContainer").innerHTML = table_contents;
          document.getElementById("mySANHelp").innerHTML = san_help_empty;
        break;
        case "DEV":
          table_contents = row_customer + row_spacer + row_custom_san;
          document.getElementById("myTableContainer").innerHTML = table_contents;
          document.getElementById("mySANHelp").innerHTML = san_help;
        break;
      }
    }
  </script>
  };

    print q{
    <h2>Is this request for a Gateway, BEM or Client?</h2>
    <select name=f_gwClient onLoad="handleSelect(this.value)" onChange="handleSelect(this.value)">
      <option selected value="">Select a Response
      <option value="gateway">Gateway
      <option value="bem">BEM
      <option value="addia">Active Directory DIA
      <option value="trustlevel">Trust Level
      <option value="endpoint">Endpoint Client
      <option value="DEV">DEV
    </select>
    <i>AD DIA, Trust Level, and Endpoint Client are clients.</i>
    <br/><br/>
    };

    print '<table><tbody id="myTableContainer"></tbody></table>';

  print "<p></p>\n";

  print "<font color=\"black\"><input type=submit value=\"Submit\"></font>\n";

  print "<p></p>\n";
  print "<p></p>\n";

  print "<div id=\"mySANHelp\"></div>";
}

print header();
print start_html("Invisinet Certificate Generation - for TAC 2.1.1+ ONLY");

print "<link rel=\"stylesheet\"\n";
print "\ttype=\"text/css\"\n";
print "\thref=\"../styles.css\"\n";
print "/>\n\n";

print "<h1><center>Invisinet Certificate Generation</center></h1>\n";
print "<h2><font color=\"red\"><center>***For use with TAC 4.1 and beyond ONLY***</center></font></h2>\n";

if(param( 'f_csr' ))
{
  $csr = param( 'f_csr');
  $customer = param( 'f_customer');
  $fqdn = param( 'f_fqdn');
#  $hostname = param( 'f_hostname');
#  $ipAddress = param( 'f_ipAddress');
  $gwSvcsFqdn = param( 'f_gwSvcsFqdn');
#  $gwSvcsIpAddress = param( 'f_gwSvcsIpAddress');
  $gwClient = param( 'f_gwClient');
  $custom_san = param( 'f_custom_san');

  if ($csr eq '')
  {
    print "Sorry, you have to enter a CSR.  You can press the back button in your browser to correct this.\n";
  }
  else
  {
    my $certsDir = "certs";

    if (!-d $certsDir)
    {
	mkdir $certsDir, 0777 or die "Unable to create Certs Directory $certsDir - $!\n";
    }

    ##########################################################################
    # Create temporary CSR file to extract info from before moving into
    # customer directory
    ##########################################################################
    #my $tmpCsrFile = "/tmp/csrFile.txt";
    my $tmpCsrFile = "tmpCsrFile.txt";
    open (TMPCSRFILE, "> $tmpCsrFile") or die "Unable to open $tmpCsrFile for writing $!\n";
    print TMPCSRFILE $csr;
    close TMPCSRFILE;

    my $tmpCsrDecode = "tmpCsrFileDecode.txt"; 
    my $openSslDecode = "openssl req -in $tmpCsrFile -noout -text > $tmpCsrDecode"; 
    system ($openSslDecode);

    open(CSR_DECODE,"<$tmpCsrDecode");

    while(my $line = <CSR_DECODE>)
    {
      chomp ($line);
      if ($line =~ m/^\s*Subject: C=(.*), ST=(.*), L=(.*), O=(.*), OU=(.*), CN=(.*)/i)
      #if ($line =~ m/^\s*Subject: CN=(.*), C=(.*), ST=(.*), L=(.*), O=(.*), OU=(.*)
      {
        $csrCountry = $1;
        $csrState = $2;
        $csrLocale = $3;
        $csrOrg = $4;
        $csrOrgUnit = $5;
        $csrCommonName = $6;
      }
    }

    #########################
    # DJ Debug
    #########################
    #print "$csrOrg\n";
    #print "$csrOrgUnit\n";
    #########################
    # DJ Debug
    #########################

    #($csrOrgNoSpaces = $csrOrg) =~s/\s*//g;
    #($csrOrgUnitNoSpaces = $csrOrgUnit) =~s/\s*//g;
    
    my $customerNoSpaces = whack_a_space($customer);

    my $customerDir = "$certsDir/customers/$customerNoSpaces";
    my $custSubDir;

    if ( defined( $fqdn ) )
    {
      $custSubDir = $customerDir . "/" . $fqdn;
    }
    elsif ( defined( $hostname ) )
    {
      $custSubDir = $customerDir . "/" . $hostname;
    }
    elsif ( defined( $ipAddress ) )
    {
      $custSubDir = $customerDir . "/" . $ipAddress;
    }
    else
    {
      $custSubDir = $customerDir . "/" . "DEV_custom_SAN";
    }

    my $csrFile = $custSubDir . "/csrFile.txt";

    if (!-d $customerDir)
    {
	mkdir $customerDir, 0777 or die "Unable to create Customer Directory $customerDir - $!\n";
    }

    if (!-d $custSubDir)
    {
	mkdir $custSubDir, 0777 or die "Unable to create Customer Sub-Directory $custSubDir - $!\n";
    }
    else
    {
        # We are using seconds in the rename for jerks who want to try to break the tool
        my $newDirectory = $custSubDir . "-" . $now;
        rename $custSubDir,$newDirectory;
	    mkdir $custSubDir, 0777 or die "Unable to create Jerk $custSubDir - $!\n";
    }

    open (CSRFILE, "> $csrFile") or die "Unable to open $csrFile for writing $!\n";
    print CSRFILE $csr;
    close CSRFILE;

    #########################################################
    # Start of certificate generation output 
    #########################################################
    print "<h2>Customer Details</h2>";

    print "<table width=\"80%\">\n";
    print "<tr>\n";
    print "<td><u><b>What you entered</b></u></td>\n";
    print "<td><u><b>What the CSR has</b></u></td>\n";
    print "</tr>\n";

    print "<tr>\n";
    print "<td>\n";
    print "Customer: $customer<br>\n";
    if ( $gwClient eq 'DEV' )
    {
      print "Custom SAN: $custom_san<br>\n";
    }
    else
    {
      print "FQDN: $fqdn<br>\n" if defined($fqdn);
#      print "Hostname: $hostname<br>\n" if defined($hostname);
#      print "MGMT IP Address: $ipAddress<br>\n" if defined($ipAddress);
      print "Gateway Services FQDN: $gwSvcsFqdn<br>\n" if defined($gwSvcsFqdn);
#      print "Gateway Services IP Address: $gwSvcsIpAddress<br>\n" if defined($gwSvcsIpAddress);
    }
    print "Gateway or Client: $gwClient<br>\n";
    print "</td>\n";

    print "<td>\n";
    print "Country: $csrCountry<br>\n";
    print "State: $csrState<br>\n";
    print "Locale: $csrLocale<br>\n";
    print "Organization: $csrOrg<br>\n";
    print "Org Unit: $csrOrgUnit<br>\n";
    print "LHID / UUID: $csrCommonName<br>\n";
    print "</td>\n";

    print "</tr>\n";
    print "</table>\n";
    print "<p></p>\n";

#SH2 - added button to restart the process for another cert

    print "<form action=\"$cgi_script\" method=\"get\">\n";
    print "<input type=\"hidden\" name=\"f_liability\" value=\"yes\">\n";
    print "<input type=submit value=\"Make Another Cert!\">\n";
    print "</form>\n";

    #########################################################
    # Start of certificate generation
    #########################################################

    my $certFile;
    my @certGenCmd;
    my $envCommand;

    my $command;
    my $uri;

    if($gwClient eq "gateway")
    {
#SH2 - add $fqdn to SAN
      if ( $fqdn ) 
      {
        push @sanFqdns, "DNS:$fqdn";
        $uri = "URI:blackridge://$fqdn/Agent/userInterface";
      }

#SH2 - if $gwSvcsFqdn is set, add it to the SAN
      if ( $gwSvcsFqdn )
      {
          push @sanFqdns, "DNS:$gwSvcsFqdn";
      } 
      $ENV{SAN}=join(",", @sanFqdns, $uri);
      $envCommand = "export $ENV{SAN}";

      $certFile = "GW_Cert.txt";
      open (CERTFILE, "> $custSubDir/$certFile") or die "Unable to open $certFile for writing $!\n";
      close CERTFILE;

      $command = "/usr/bin/openssl ca -config $subCaDir/sub-ca.conf -in $csrFile -out $custSubDir/$certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch";
    }
    elsif($gwClient eq "addia")
    {
#SH2 - add $fqdn to SAN; set $uri based on actual Mgmt FQDN
      if ( $fqdn ) 
      {
        push @sanFqdns, "DNS:$fqdn";
        $uri = "URI:blackridge://$fqdn/Agent/identityInsertion";
      }
      $ENV{SAN}=join(",", @sanFqdns, $uri);
      $envCommand = "export $ENV{SAN}";

      $certFile = "GW_Cert.txt";
      open (CERTFILE, "> $custSubDir/$certFile") or die "Unable to open $certFile for writing $!\n";
      close CERTFILE;

      $command = "/usr/bin/openssl ca -config $subCaDir/sub-ca.conf -in $csrFile -out $custSubDir/$certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch";
    }
    elsif($gwClient eq "bem")
    {
#SH2 - add $fqdn to SAN; set $uri based on actual Mgmt FQDN
      if ( $fqdn ) 
      {
        push @sanFqdns, "DNS:$fqdn";
        $uri = "URI:blackridge://$fqdn/Agent/userInterface";
      }
      $ENV{SAN}=join(",", @sanFqdns, $uri);
      $envCommand = "export $ENV{SAN}";

      $certFile = "BEM_Cert.txt";
      open (CERTFILE, "> $custSubDir/$certFile") or die "Unable to open $certFile for writing $!\n";
      close CERTFILE;

      $command = "/usr/bin/openssl ca -config $subCaDir/sub-ca.conf -in $csrFile -out $custSubDir/$certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch";
    }
    elsif($gwClient eq "trustlevel")
    {
#SH2 - add $fqdn to SAN; set $uri based on actual Mgmt FQDN
      if ( $fqdn ) 
      {
        push @sanFqdns, "DNS:$fqdn";
        $uri = "URI:blackridge://$fqdn/Agent/trustlevel";
      }
      $ENV{SAN}=join(",", @sanFqdns, $uri);
      $envCommand = "export $ENV{SAN}";

      $certFile = "TrustLevel_Cert.txt";
      open (CERTFILE, "> $custSubDir/$certFile") or die "Unable to open $certFile for writing $!\n";
      close CERTFILE;

      $command = "/usr/bin/openssl ca -config $subCaDir/sub-ca.conf -in $csrFile -out $custSubDir/$certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch";
    }
    elsif($gwClient eq "endpoint")
    {
#SH2 - add $fqdn to SAN; set $uri based on actual Mgmt FQDN
      if ( $fqdn ) 
      {
        push @sanFqdns, "DNS:$fqdn";
        $uri = "URI:blackridge://$fqdn/Agent/identityActivation";
      }
      $ENV{SAN}=join(",", @sanFqdns, $uri);
      $envCommand = "export $ENV{SAN}";

      $certFile = "Endpoint_Client_Cert.txt";
      open (CERTFILE, "> $custSubDir/$certFile") or die "Unable to open $certFile for writing $!\n";
      close CERTFILE;
	      
      $command = "/usr/bin/openssl ca -config $subCaDir/sub-ca.conf -in $csrFile -out $custSubDir/$certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch";
    }
    elsif ( $gwClient eq 'DEV' )
    {
      $ENV{SAN}=$custom_san;
      $envCommand = "export $ENV{SAN}";

      $certFile = "DEV_Custom_SAN_Cert.txt";
      open (CERTFILE, "> $custSubDir/$certFile") or die "Unable to open $certFile for writing $!\n";
      close CERTFILE;
	      
      $command = "/usr/bin/openssl ca -config $subCaDir/sub-ca.conf -in $csrFile -out $custSubDir/$certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch";
    }
    else
    {
      $certFile = "GW_Client_Cert.txt";
      open (CERTFILE, "> $custSubDir/$certFile") or die "Unable to open $certFile for writing $!\n";
      close CERTFILE;

      $command = "/usr/bin/openssl ca -config $subCaDir/sub-ca.conf -in $csrFile -out $custSubDir/$certFile -notext -extensions serverclient_ext -key Bl4ckR!dg3 -batch";
    }

    system ($envCommand);
    system ($command);

    print "<h2>Certificate Details</h2>";

#########
# DJ Debug
#########
#print "Debug stuff<br>\n";
#print "The certificate file is <a href=\"$custSubDir/$certFile\">Here</a><br>\n";
#print "The CA chain file is <a href=\"certificate_trust_chain.txt\">Here</a><br>\n";
#print "End debug stuff<br>\n";
#########
# DJ Debug
#########

    print "<b>Your $certFile is:</b><br>\n";
    print "<font color=\"#FF0000\">\n";
    open (CERTFILE, "$custSubDir/$certFile") or die "Unable to open $certFile for reading $!\n";
    while (<CERTFILE>)
    {
      chomp;
      print "$_<br>\n";
    }
    close(CERTFILE);
    print "</font>\n";

    print "<p></p>\n";

    print "<b>Your I-CA.txt is:</b><br>\n";
    print "<font color=\"#FF0000\">\n";
    open (SUBCACRT, "$subCaDir/sub-ca.crt") or die "Unable to open sub-ca.crt for reading $!\n";
    while (<SUBCACRT>)
    {
      chomp;
      print "$_<br>\n";
    }
    close(SUBCACRT);
    print "</font>\n";

    print "<p></p>\n";

    print "<b>Your R-CA.txt is:</b><br>\n";
    print "<font color=\"#FF0000\">\n";
    open (ROOTCACRT, "$rootCaDir/root-ca.crt") or die "Unable to open root-ca.crt for reading $!\n";
    while (<ROOTCACRT>)
    {
      chomp;
      print "$_<br>\n";
    }
    close(ROOTCACRT);

    #system('$mkdir -p /certs/$customer');
    #system('$echo $csr > /certs/$customer/csrFile.txt');

    #open(CSRFILE,">/certs/$customer/csrFile.txt");

    #print CSRFILE $csr;
  
    ###############################
    # Write Julia's Report File
    ###############################
#SH2    updateTrackingReport();
#SH2    updateTrackingDB();
  }
}
elsif(param('f_customer'))
{ # Begin - section to get CSR
  $customer = param('f_customer');
  $fqdn = param('f_fqdn');
#  $hostname = param('f_hostname');
#  $ipAddress = param('f_ipAddress');
  $gwSvcsFqdn = param('f_gwSvcsFqdn');
#  $gwSvcsIpAddress = param('f_gwSvcsIpAddress');
  $custom_san = param('f_custom_san');
  $gwClient = param('f_gwClient');

  if ( $customer eq '' ) 
  {
    print "Sorry, you have to enter Customer information.  You can press the back button in your browser to correct this.\n";
  }
  # Gateway fields not set correctly
  elsif ( $gwClient eq 'gateway' and (($fqdn eq '') or ($gwSvcsFqdn eq '' ) ) )
  {
    print "Sorry, you have to enter FQDN information.  You can press the back button in your browser to correct this.\n";
  }
  # BEM, ADDIA, Trust Level fields not set correctly
  elsif ( ( $gwClient eq 'bem' or $gwClient eq 'addia' or $gwClient eq 'trustlevel') and ( $fqdn eq '' ) )
  {
    print "Sorry, you have to enter FQDN information.  You can press the back button in your browser to correct this.\n";
  }
  # Endpoint client fields not set correctly
  elsif ( ($gwClient eq 'endpoint' ) and ( $fqdn eq '' ))
  {
    print "Sorry, you have to enter FQDN information.  You can press the back button in your browser to correct this.\n";
  }
  # Custom SAN field not set correctly
  elsif ( ($gwClient eq 'DEV' ) and ( $custom_san eq '' ) )
  {
    print "Sorry, you have to enter a correctly-formatted SAN .  You can press the back button in your browser to correct this.\n";
  }
  else
  {
    print "<h2>Customer Details</h2>";
    print "Customer is $customer<br>\n";
    if ( $gwClient eq 'DEV' )
    {
      print "Custom SAN is $custom_san<br>\n" if defined($custom_san);
    }
    else
    {
      print "FQDN is $fqdn<br>\n" if defined($fqdn);
#      print "Hostname is $hostname<br>\n" if defined($hostname);
#      print "MGMT IP Address is $ipAddress<br>\n" if defined($ipAddress);
      print "Gateway Services FQDN is $gwSvcsFqdn<br>\n" if defined($gwSvcsFqdn);
#      print "Gateway Services IP Address is $gwSvcsIpAddress<br>\n" if defined($gwSvcsIpAddress);
      print "Gateway or Client is $gwClient<br>\n" if defined($gwClient);
    }

    print "<p></p>\n";

    print "Paste CSR here...<br>\n";

    print "<font color=\"black\">\n";
    print "<form action=\"$cgi_script\" method=\"post\">\n";
    print "<table>\n";

      print "<tr>\n";
      print "<td><textarea rows=30 cols=78 name=f_csr></textarea></td>\n";
      print "</tr>\n";

    print "</table>\n";

    print "<p></p>\n";

    print "<input type=hidden name=f_customer value=\"$customer\">\n" if defined($customer);
    print "<input type=hidden name=f_fqdn value=\"$fqdn\">\n" if defined($fqdn);
#    print "<input type=hidden name=f_hostname value=\"$hostname\">\n" if defined($hostname);
#    print "<input type=hidden name=f_ipAddress value=\"$ipAddress\">\n" if defined($ipAddress);
    print "<input type=hidden name=f_gwSvcsFqdn value=\"$gwSvcsFqdn\">\n" if defined($gwSvcsFqdn);
#    print "<input type=hidden name=f_gwSvcsIpAddress value=\"$gwSvcsIpAddress\">\n" if defined($gwSvcsIpAddress);
    print "<input type=hidden name=f_gwClient value=\"$gwClient\">\n" if defined($gwClient);
    print "<input type=hidden name=f_custom_san value=\"$custom_san\">\n" if defined($custom_san);

    print "<input type=submit value=\"Submit\">\n";
    print "</form>\n";
    print "</font>\n";

  }
} # End - section to get CSR
elsif(param( 'f_liability' ))
{
  $acceptLiability = param( 'f_liability');

  if ($acceptLiability eq 'no')
  {
    print "Sorry but you must accept the Liability Notice before proceeding.  Each time.  Every time.  We are tracking you.\n";
  }
  else
  {
    getCustomerInfo();
  }
}
else 
{
  acceptLiability();
}

print end_html();
